[project]
name = "task"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nox1KCL", email = "korshunov.maks09@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "playwright>=1.62.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.3",
]

[project.scripts]
task = "task:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"

[tool.pyright]
venvPath = "."
venv = ".venv"
